_wandb:
    value:
        cli_version: 0.29.0
        e:
            nb4did1moie8hditaaz5uhlb1e7jby2n:
                email: kn020920006@gmail.com
                executable: D:\Anaconda3\envs\ppe_backend\python.exe
                git:
                    commit: 218372564c8825bbd5654dbc9fa747be4664f25d
                    remote: https://github.com/volethanhtrieu/YOLOv8.git
                host: Khanh
                os: Windows-10-10.0.26200-SP0
                program: <python with no main file>
                python: CPython 3.10.20
                root: D:\253\PYTHON & ML\PROJECT\PPE_Ablation_Backend_YOLOv8x\ppe_ablation_backend
                startedAt: "2026-08-27T15:02:26.380069Z"
                writerId: nb4did1moie8hditaaz5uhlb1e7jby2n
        m: []
        python_version: 3.10.20
        t:
            "3":
                - 2
                - 13
            "4": 3.10.20
            "5": 0.29.0
            "8":
                - 3
            "12": 0.29.0
            "13": windows-amd64
